dist: xenial
sudo: true
before_script:
  - sudo apt-get install -y git-ftp
  - git config git-ftp.url $FTP_SERVER
  - git config git-ftp.user $FTP_USER
  - git config git-ftp.password $FTP_PWD
script:
  - git ftp init
  - git ftp push --force
  #- ls -la
addons:
  apt:
    update: true