dist: xenial
sudo: true
before_script:
  - sudo apt-get install -y git-ftp
script:
  - ping http://giveaccess.ga/ping.php
  - git config git-ftp.url $FTP_SERVER
  - git config git-ftp.user $FTP_USER
  - git config git-ftp.password $FTP_PWD
  - git ftp init
addons:
  apt:
    update: true
