language: php
dist: xenial
sudo: true
before_script:
  - git config git-ftp.url $FTP_SERVER
  - git config git-ftp.user $FTP_USER
  - git config git-ftp.password $FTP_PWD
before_install:
  - sudo apt-get install -y git-ftp
addons:
  apt:
    update: true
